name: Reporte de Cobertura

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cov-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario si luego usamos ramas como gh-pages

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install tools
        run: |
          dotnet tool install -g docfx
          dotnet tool install -g dotnet-reportgenerator-globaltool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Ejecutar pruebas y generar cobertura
        run: |
          cd MyMath
          dotnet test --collect:"XPlat Code Coverage"
          reportgenerator "-reports:$report_path" "-targetdir:MyMath/Cobertura" -reporttypes:Html

      - name: Deploy a GitHub Pages sin borrar archivos previos
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: MyMath/Cobertura
          publish_branch: gh-pages
          destination_dir: cov-report
          keep_files: true  # <--- Esto evita borrar contenido anterior
