name: Crear y Publicar NuGet

on:
  workflow_dispatch:
    inputs:
      codigo:
        description: '2022074262'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependencias
        run: dotnet restore MyMath/Math.Lib/Math.Lib.csproj

      - name: Actualizar versión en csproj
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ github.event.inputs.codigo }}</Version>|" MyMath/Math.Lib/Math.Lib.csproj

      - name: Compilar proyecto
        run: dotnet build MyMath/Math.Lib/Math.Lib.csproj --configuration Release --no-restore

      - name: Empaquetar NuGet
        run: dotnet pack MyMath/Math.Lib/Math.Lib.csproj --configuration Release --no-build --output .

      - name: Publicar en GitHub Packages
        run: dotnet nuget push *.nupkg --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.codigo }}
          name: "Release ${{ github.event.inputs.codigo }}"
          files: |
            *.nupkg
